#!/bin/csh
#
echo  compute charges and optimize with BOSS
#     starting from a z-matrix moleculename -
#     this is used to refine an initial structure
#
# usage - xZCM1A moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp $argv[1].z optzmat
cp $argv[1].z zmatol.z

csh $BOSSdir/scripts/OPTcmd >& log 
rm optzmat
cp sum optzmat
cp optzmat zmat1-OPLS
csh $BOSSdir/scripts/AM1SPcmd >& log
rm optzmat
cp sum optzmat
cp optzmat zmat1-CM1A
./decm1.out
mv decm1out optzmat
cp optzmat zmat1-new

csh $BOSSdir/scripts/OPTcmd >& log
rm optzmat
cp sum optzmat
cp optzmat zmat2-OPLS
csh $BOSSdir/scripts/AM1SPcmd >& log
rm optzmat
cp sum optzmat
cp optzmat zmat2-CM1A
./decm1.out
mv decm1out optzmat
cp optzmat zmat2-new

csh $BOSSdir/scripts/OPTcmd >& log
rm optzmat
cp sum optzmat
cp optzmat zmat3-OPLS
csh $BOSSdir/scripts/AM1SPcmd >& log
rm optzmat
cp sum optzmat
cp optzmat zmat3-CM1A
./decm1.out
mv decm1out optzmat
cp optzmat zmat3-new

csh $BOSSdir/scripts/OPTcmd >& log

echo  output is in out, sum and plt.pdb
rm optzmat
rm zmatol.z
#
exit
